### ISSUE TITLE
How to encrypt using only a public key string and no certificate

### ISSUE THREAD

**Issue by airamez** [dvsekhvalnov/jose-jwt#102]
This maybe a stupid question but I have a requirement to implement a current JavaScript code in C#. However, following the examples, they all use a Certificate and in case I have to encrypting the content in the client side using a public key and following information:
JWE.Encrypt.Algorithm: RSA-OAEP-256
JWE.Encrypt.ContentAlgorithm: A256GCM
JWE.Encrypt.KeyName: testName
The PublicKey is something like: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFpcmXXXXXXXXXXL1A3b0pIUAprWHhqMVhaT0JZckttSmM1cmJDT2ZUTTkrazBuVzBQL0kwUi9SM0dlWmJhV2R3UTN2dDFSWDV6OHJhaVpjVFpOCm1EYTFxVGN2TmE4bTV3NVh1b1gzUFZtY3V0RXZqZU94ZE9wV3hpMTV4Y1RBb1lUZVVsTFk1ckRFaHh6QXVybUUKN2lLWHhhUXdlTFJ5dXNqTGFkVkNjVElKMzdMRmXXXXXXXXXpGVDRFQ1FZYkxrNkJhdGltOTV5TnJCbwpvWVd6aEdESzZ1YWN5QWJic21aeEh4UUdUTjhPcWppNElXeDJweXVyTnBQbGVkaFhjRkpPWjlWSldOU3pXMGp5CmtXXXXXXXXXXwWUhIMlhRSml3cWJOV1RMclFvdkRHT1ZwU3NPT2JST1lCeWlDQTRQQVVxcU1iM1AxOHVvUWsKdndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
Any help will be much appreciated.
Thanks

**Comment by dvsekhvalnov** [comment]
Hi @airamez ,

mind code sample in JS that you are trying to migrate? Trying to understand what's your PublicKey string is.

**Comment by airamez** [comment]
```LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFpcmRBeTl3ZDFGTE1BL1A3b0pIUAprWHhqMVhaT0JZckttSmM1cmJDT2ZUTTkrazBuVzBQL0kwUi9SM0dlWmJhV2R3UTN2dDFSWDV6OHJhaVpjVFpOCm1EYTFxVGN2TmE4bTV3NVh1b1gzUFZtY3V0RXZqZU94ZE9wV3hpMTV4Y1RBb1lUZVVsTFk1ckRFaHh6QXVybUUKN2lLWHhhUXdlTFJ5dXNqTGFkVkNjVElKMzdMRmY2TzZ6VnJRck9lQkpGVDRFQ1FZYkxrNkJhdGltOTV5TnJCbwpvWVd6aEdESzZ1YWN5QWJic21aeEh4UUdUTjhPcWppNElXeDJweXVyTnBQbGVkaFhjRkpPWjlWSldOU3pXMGp5CmtEdzhpU3ViNDZwWUhIMlhRSml3cWJOV1RMclFvdkRHT1ZwU3NPT2JST1lCeWlDQTRQQVVxcU1iM1AxOHVvUWsKdndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==```

**Comment by dvsekhvalnov** [comment]
Ok, so it is:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAirdAy9wd1FLMA/P7oJHP
kXxj1XZOBYrKmJc5rbCOfTM9+k0nW0P/I0R/R3GeZbaWdwQ3vt1RX5z8raiZcTZN
mDa1qTcvNa8m5w5XuoX3PVmcutEvjeOxdOpWxi15xcTAoYTeUlLY5rDEhxzAurmE
7iKXxaQweLRyusjLadVCcTIJ37LFf6O6zVrQrOeBJFT4ECQYbLk6Batim95yNrBo
oYWzhGDK6uacyAbbsmZxHxQGTN8Oqji4IWx2pyurNpPledhXcFJOZ9VJWNSzW0jy
kDw8iSub46pYHH2XQJiwqbNWTLrQovDGOVpSsOObROYByiCA4PAUqqMb3P18uoQk
vwIDAQAB
-----END PUBLIC KEY-----
```

, well you can't read it directly in .NET, because `X509Certificate2` expects certificate, not raw key (e.g. `----- BEGIN CERTIFICATE -----`).

Possible options:
1. Use certificate instead of bare public key. Pretty much same thing.

2. Try something like that: https://stackoverflow.com/questions/11506891/how-to-load-the-rsa-public-key-from-file-in-c-sharp
   
    Though i don't recommend, too much code, security implications unknown.

3. May be switch to JWK (json format for keys). library don't support it directly but there were several questions how to handle it, i'll point you to if you want this route.

**Comment by airamez** [comment]
Thank you very much for the prompt response. I am just wondering about the option 1. May I generate a certificate from the public key directly or do I have to request changes on the server side validation as well? I have no control on the server side of this solution.
The only think they will provide me is the public key and the endpoint.

**Comment by dvsekhvalnov** [comment]
No, i doubt you can create certificate from public key only. After all certificates should be signed :)

Can they provide certificate?
Or may be key in JWK format?

Otherwise you can take a look at something: 
https://www.codeproject.com/articles/25487/cryptographic-interoperability-keys

or

https://gist.github.com/stormwild/7887264

**Comment by airamez** [comment]
Thank you very much.
I appreciated the quick assistance and suggestion of possible options.
You rocks!

**Comment by dvsekhvalnov** [comment]
Let me know how it goes, we can probably figure something out.

**Comment by airamez** [comment]
I tried to find a solution but nothing worked. And looks like there is no C# API to acomplish what that JavaScript API (https://www.npmjs.com/package/node-jose/v/1.0.0) is doing (Generate a JOSE token using just a public key). Looks there is one for Java. I will try it.
