### ISSUE TITLE
.Net Standard 2.1 Support

### ISSUE THREAD

**Issue by msdickinson** [dvsekhvalnov/jose-jwt#148]
Hi There!
When running an ASP.NET Core 3.1 Web API project from a Linux Docker container we received the following error:
System.DllNotFoundException: Unable to load shared library 'bcrypt.dll' or one of its dependencies.
When compiling the master of Jose-Jwt locally into our project it works just fine.
It seems like 2.6.1 does not support .NET Standard 2.1 is this the reason that we see this exception when we use the Nuget package?
If so, do you feel that this will be resolved in the next release?  Thanks!

**Comment by dvsekhvalnov** [comment]
Hi @msdickinson ,

that's because you are using some crypto stuff that requires native library (e.g. not supported in managed .net).

See: https://github.com/dvsekhvalnov/jose-jwt/issues/45https://github.com/dvsekhvalnov/jose-jwt/issues/45

If you failing with AES GCM - than there is good news, we gonna ship update soonish that will use new AesGcm managed classes added to .netcore3, so may be can solve your issues.

If something else, please feel free to share more details so we can discuss and see what's going on.

**Comment by msdickinson** [comment]
Thank you, Feel free to close this then, and I will track #45/watch for the next update.

**Comment by dvsekhvalnov** [comment]
Just in case it has been released.
