### ISSUE TITLE
Sign with alg ES384 and encryption with alg ECDH-ES+A256KW is supported in .Net Core 3.1

### ISSUE THREAD

**Issue by venkatpoluri** [dvsekhvalnov/jose-jwt#163]
Hello Dear,

Is it Sign with alg ES384 and encryption with alg ECDH-ES+A256KW  supported in .Net Core 3.1?

I am loading the keys from json file. I can generate Cng key from the json file for signing and encryption.

But Encryption is not proper I couldn't decrypt it.

I'm using .Net Core 3.1

Please share the implementation plan.

**Comment by dvsekhvalnov** [comment]
Hi @venkatpoluri , 

have you read https://github.com/dvsekhvalnov/jose-jwt#notes ?

**Comment by venkatpoluri** [comment]
Thanks for your reply. As per Notes, I can't use more than 256-bit keys. Is it support in  .Net 5.0?

**Comment by dvsekhvalnov** [comment]
Hi @venkatpoluri ,  yeah it may be not compatible. I'd recommend to test ECDH-ES+A128KW if you can. And see if it works to isolate issue. (If it still not - let's troubleshoot more).

I can try to get .net 5 environment to test, but the issue was inside Microsoft's CNG native driver for windows, unlikely .net version matters, though i'll try to verify.

**Comment by dvsekhvalnov** [comment]
Hey, i've replied in github.

**Comment by venkatpoluri** [comment]
Thanks for reply.
