### ISSUE TITLE
Enable support for non-exportable keys in .NET 4.6 via GetRSAPrivateKey()

### ISSUE THREAD

**Issue by sandersaares** [dvsekhvalnov/jose-jwt#21]
.NET Framework 4.6 introduced `X509Certificate2.GetRSAPrivateKey()` which returns an `RSACng` and enables modern cryptographic algorithms to be used without the need to re-import keys. It would be desirable for jose-jwt to support this natively, as exportable keys are a security problem.

Not sure how to best integrate this, especially as it seems to be .NET 4.6+ only (or perhaps I am mistaken). Regardless, I am attaching a sample project that demonstrates the implementation by overriding the relevant `IKeyManagement` and `IJwsAlgorithm` implementations.

[ConsoleApplication5.zip](https://github.com/dvsekhvalnov/jose-jwt/files/295668/ConsoleApplication5.zip)

**Comment by dvsekhvalnov** [comment]
Hey @sandersaares , first of all thanks for sample code !

Well, i had idea to unify key management and accept `CngKey` to all algorithms which can enable new features in latest .NET versions. But it will likely not going to happen until version 3.0 since it will include some major changes in interface and can break backward compatibility with existing clients.

As for now, primary effort for v2.0 to support both .netcore out of box. And than with v3.0 probably major cleanup and unification.

**Comment by sandersaares** [comment]
Understood. I look forward to the new features in 3.0 then. Thanks for making this library, it is very nice to have such a full-featured JOSE implementation available!

**Comment by nathan-alden** [comment]
I wish this was in the library now. As it stands, it makes it completely unusable for me. Private keys should almost never be marked exportable in a production environment.

**Comment by dvsekhvalnov** [comment]
Hi @nathan-alden the issue is about supporting new .NET 4.6 API. Which is currently not supported because library target .NET 4.0 and above. 

But there is no requirement to mark your private keys as exportable, it's some misunderstanding. `jose-jwt` is don't care and not aware about how you managing your private keys.

What exact problem you are facing?

**Comment by sandersaares** [comment]
In short, the problem is that using the pre-4.6 methods from X509Certificate2 for asymmetric cryptography does not work with modern algorithms. For example, look at [RsaKeyManagement.Unwrap()](https://github.com/dvsekhvalnov/jose-jwt/blob/master/JWT/jwa/RsaKeyManagement.cs#L33-L34).

The code here first **extracts the private key** and imports it as a CngKey. If your X509Certificate2 was loaded with a non-exportable key, this will fail. I also see an RSA key being exported by `RsaPssUsingSha`. Additionally, I suspect there are jose-jwt functions that do not work with non-exportable keys but where the export-import operation pair must be done by client code (I think this was the case with the example code used in my original post).

**Comment by nathan-alden** [comment]
My team relies on loading non-exportable private keys from things like resource files or the Windows certificate store, then passing them to `JwtSecurityTokenHandler` for use in signing. We also target .NET 4.6.1. @sandersaares, if I am understanding you correctly, jose-jwt cannot be used for this scenario. Is that correct?

**Comment by dvsekhvalnov** [comment]
@sandersaares ahh.. yeah, you right. Still doing conversion between `RSACryptoProvider` and `CngKey`.   Damn it :) I think we need to enable both types of keys in such cases. Make sense?

@nathan-alden depends on what algos you are using. RSA-OAEP-256 doing re-import because of different underlying API. Rest of algos - should not, so you can just use appropriate RSACryptoProvider with SHA2 enabled.

**Comment by dvsekhvalnov** [comment]
@sandersaares , as a thought, may be just extract RsaOaep256KeyManagement and require `CngKey`? Will it solve your issue? Still should be compatible with < .Net 4.6 versions.

**Comment by sandersaares** [comment]
@nathan-alden I use reflection to replace the implementations with one that use the 4.6 API, as demonstrated in the attachment in my original post here. The attached code above is itself only a minimal proof of concept and breaks existing functionality by *only* working with CngKey.

@dvsekhvalnov At first impression, what you say does indeed sound sensible. If I can pass in a `CngKey` to jose-jwt instead of `RSACryptoServiceProvider` then yes, I think it would solve the problem. I can then use the 4.6 API to get the `CngKey` in my own code and jose-jwt can remain compatible with older versions of .NET.

**Comment by dvsekhvalnov** [comment]
@sandersaares , check it out: https://github.com/dvsekhvalnov/jose-jwt/commit/66a80257e5e5ffa16d69c1931fbc46974047f9c3

is it looks good?

**Comment by sandersaares** [comment]
Well, it helps but does not go all the way. This change adds support for CngKey input to RSA-OAEP-256 but not to all other algorithms, so there is still something missing. Granted, it might not be technically necessary to use CngKey with older algorithms (e.g. RSA-OAEP) but app code should not need to know this - it should be possible to just pass a CngKey to every algorithm, as this enables all of them to function correctly with non-exportable keys.

**Comment by dvsekhvalnov** [comment]
Yeah, X509Certificate2.GetRSAPublicKey() returns just `RSA` object which is not `CngKey`.

Ok, i think i can handle that, .net 4.6 is much more aligned with .netcore than previous versions.

With .net4.5 and below `RSA` doesn't  support OAEP256 unfortunately. So either re-export key to `CngKey`, which is bad or require `CngKey` directly.

**Comment by dvsekhvalnov** [comment]
@sandersaares if you still here, is this one looks better finally:
https://github.com/dvsekhvalnov/jose-jwt/commit/20c3eb384881716fb3bc2b6510c36d4113e66413#diff-99de09501d837271d14a488de8975bff

?

**Comment by dvsekhvalnov** [comment]
Code is in `master`. Will be part of v2.2 nuget.org release.

**Comment by dvsekhvalnov** [comment]
released to nuget.org
