### ISSUE TITLE
Which encryption works with FIPS?

### ISSUE THREAD

**Issue by Leonidnei** [dvsekhvalnov/jose-jwt#38]
We use JweAlgorithm.A256KW, JweEncryption.A256CBC_HS512 encryption. 
On FIPS enabled environment this fails with:

Message=System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS 

validated cryptographic algorithms.
   at System.Security.Cryptography.AesManaged..ctor()
   at Jose.AesKeyWrap.AesEnc(Byte[] sharedKey, Byte[] plainText)
   at Jose.AesKeyWrap.Wrap(Byte[] cek, Byte[] kek)
   at Jose.AesKeyWrapManagement.WrapNewKey(Int32 cekSizeBits, Object key, IDictionary`2 header)
   at Jose.JWT.Encode(String payload, Object key, JweAlgorithm alg, JweEncryption enc, Nullable`1 

compression, IDictionary`2 extraHeaders)

Which encryption is FIPS compliant?

**Comment by dvsekhvalnov** [comment]
Hi @Leonidnei,

looks like `AesManaged` is not FIPS complaint. Need to check list of replacements, nobody asked about FIPS before.

**Comment by dvsekhvalnov** [comment]
@Leonidnei , i'll make update to use FIPS complaint CSP providers for AES in next version.

In the mean time you can use any CNG powered algos, for instance: RSA_OAEP_256 + A128GCM (or A192GCM or A256GCM)

**Comment by Leonidnei** [comment]
Great, thanks.

Leonid Neishtadt
Next Generation Solution Group
McKESSON IMAGING & WORKFLOW SOLUTIONS
Phone: +972 3 679 7330
Cell phone: +972 52 600 6589
Fax: +972 3 647.8593
Email: Leonid.Neishtadt@McKesson.com<mailto:Leonid.Neishtadt@McKesson.com>
www.mckesson.com/cardiology<http://www.mckesson.com/cardiology>

**Comment by andresjacobo** [comment]
@dvsekhvalnov,

First of all, your library is great! I'm currently heading a project at Robert McNeel & Associates. We make [Rhino](http://www.rhino3d.com), a popular 3D modeling software.

I am using your library to create JWTs to represent license objects between the client and server. Everything is flawless. However, we have a lot of US Government contractors who have FIPS mode enabled on their machines. This is the exception we get:
![pasted_image_at_2016_11_23_04_28_pm](https://cloud.githubusercontent.com/assets/13170182/20583398/4e1e2c70-b19e-11e6-88f2-40dd77b379d3.png)

I am willing to create a fork to fix the problem since the project is important to us if you are not willing or able to fix it in a timely manner. 

I'm looking forward to your response.

**Comment by dvsekhvalnov** [comment]
Hi @andresjacobo , yeah there were couple requests about fixing FIPS non compliant algorithms in a library. You can track them via  https://github.com/dvsekhvalnov/jose-jwt/labels/FIPS

I have another feature to put forward before FIPS, so i don't mind if you contribute pull request. I'll look again later today to check which algos are not compliant and can provide you some list.

**Comment by dvsekhvalnov** [comment]
So, with FIPS enabled mode i'm getting just 39 failed tests, it appears the offending stuff in:

1. AesKeyWrap.cs using `AesManaged` 
2. RsaUsingSha.cs using `SHA256.Create()`, `SHA384.Create()`, `SHA512.Create()` that by default returning corresponding managed implementation of SHA.

**Comment by andresjacobo** [comment]
Thanks for the list! It's currently a holiday weekend here in the US, but I'll do a pull request first thing next week.

**Comment by dvsekhvalnov** [comment]
Thank you for contribution, release to nuget.org
