### ISSUE TITLE
AesEnc/Dec for NetStandard 1.4

### ISSUE THREAD

**Issue by dhjf** [dvsekhvalnov/jose-jwt#39]
Hi

Can you give an estimate on when AesEnc/Dec functionality (jose-jwt/crypto/AesKeyWrap.cs) is going to implemented for NetStandard 1.4? 

/Christian

**Comment by dvsekhvalnov** [comment]
Hi @dhjf ,

will be definitely not in next version (2.1) since there are other requests pending. Most likely v2.2.

It's hard to give any exact ETA because i'm working on it in spare time. But i'm accepting pull requests if somebody wants to add it :) All unit tests are in-place and i'll do cross-verification with other libraries.

**Comment by dhjf** [comment]
Alright, thanks for the quick answer. Might be working on a pull request then ;-)

**Comment by dhjf** [comment]
So, I can see that the pull request got merged, which is great.
When can I expect a new package version to be on nuget?

**Comment by dvsekhvalnov** [comment]
Hey, i'll try to cut off v2.0.2 release this week.

**Comment by dvsekhvalnov** [comment]
v2.0.2 pushed to nuget
