### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by vaindil** [dvsekhvalnov/jose-jwt#45]
I've been using this as I develop on my Windows machine and it's awesome! I'm publishing to an Ubuntu machine, however, and I'm getting an exception that bcrypt.dll could not be found. That's obviously something on Windows machines and not Ubuntu. Is there something I can do to fix this? I tried manually copying bcrypt.dll from my Windows machine, the same error occurs.

I'm specifically calling this code to encrypt my tokens. Signing works correctly, but encrypting does not.

``` csharp
// JwtSigningKey is a byte array
// JwtEncryptionKey is a byte array

var payload = new Jwt
{
    // create JWT
};

var signedToken = JWT.Encode(payload, JwtSigningKey, JwsAlgorithm.HS256);

return JWT.Encode(signedToken, JwtEncryptionKey, JweAlgorithm.DIR, JweEncryption.A256GCM, JweCompression.DEF);
```

**Comment by dvsekhvalnov** [comment]
Hi @vaindil ,

well.. last time i checked library on *nix it has way more failed tests than on windows. Some stuff simply not implement in netcore for *nix, some relies on bcrypt.dll.

Most likely AES-GCM will NOT work but you can try AES+CBC+HMAC instead.

I haven't really looked at what it will take to fully support linux yet.

**Comment by psibernetic** [comment]
Does this apply to ose.JweAlgorithm.RSA_OAEP and Jose.JweEncryption.A256GCM these will need to work on linux for my deployment strategy.

**Comment by dvsekhvalnov** [comment]
RSA_OAEP and RSA_OAEP_256 - probably will work, at least they are implemented in corefx api (but try on linux)

AES GCM not, not on corefx yet, see: https://github.com/dotnet/corefx/issues/7023

**Comment by psibernetic** [comment]
Do any of the supported encryption types work, all i'm trying to do is encrypt using a cert, don't care the algorithm at this point.

**Comment by dvsekhvalnov** [comment]
AES+CBC+HMAC: A128CBC-HS256, A192CBC-HS384, A256CBC-HS512, A128GCM, A192GCM, A256GCM

**Comment by justinhelgerson** [comment]
FYI, it looks like https://github.com/dotnet/corefx/issues/7023 has been closed, although not released.  I also was running into an issue with `bcrypt.dll` missing while running on AWS Lambda.

**Comment by dvsekhvalnov** [comment]
@justinhelgerson , thanks for update !  Definitely would be nice to update library implementation with managed AES GCM api instead of native hell. 

Do you know if release version that will include it was announced ?

**Comment by justinhelgerson** [comment]
It looks like it's being added in .NET Core 3.0 which I presume will be [.NET Standard 2.1](https://github.com/dotnet/standard/milestone/3)?  I don't know for certain though.

**Comment by dvsekhvalnov** [comment]
ok, will ask around

**Comment by dvsekhvalnov** [comment]
https://github.com/dotnet/corefx/pull/31389#issuecomment-431625999
Given AES-GCM it's scheduled for .netcore 3.0, will add support once it release in 2019.

**Comment by justinhelgerson** [comment]
Thanks @dvsekhvalnov, appreciate your contributions to this library!

**Comment by a-sinha** [comment]
Hi @dvsekhvalnov, It seems this is fixed in .Net core 3.1, any plans for fixing this one?

**Comment by dvsekhvalnov** [comment]
Hey @a-sinha , thanks for heads up, missed when it was released.
Yep, will take a look what it takes to switch to new managed crypto implementations.

**Comment by ShaikhArmaan** [comment]
Hi @dvsekhvalnov , I am facing the same issue. I am using Jose.JWT.Encode method with JweAlgorithm.RSA_OAEP_256 and JweEncryption.A256GCM. I am able to encode on local windows machine and on a windows IIS server but when I am hosting the same on linux server, I am getting an exception saying bcrypt.dll was not found. I'm posting the stack trace below. My version of .Net Core is 2.2. Pls Help!!!

"Exception":"System.DllNotFoundException: Unable to load shared library 'bcrypt.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbcrypt.dll: cannot open shared object file: No such file or directory\n   at Jose.native.BCrypt.BCryptOpenAlgorithmProvider(IntPtr& phAlgorithm, String pszAlgId, String pszImplementation, UInt32 dwFlags)\n   at Jose.AesGcm.OpenAlgorithmProvider(String alg, String provider, String chainingMode)\n   at Jose.AesGcm.Encrypt(Byte[] key, Byte[] iv, Byte[] aad, Byte[] plainText)\n   at Jose.AesGcmEncryption.Encrypt(Byte[] aad, Byte[] plainText, Byte[] cek)\n   at Jose.JWT.EncodeBytes(Byte[] payload, Object key, JweAlgorithm alg, JweEncryption enc, Nullable`1 compression, IDictionary`2 extraHeaders, JwtSettings settings)\n

**Comment by gjermystreeva** [comment]
Hi @dvsekhvalnov - I took a look and the support in net standard 2.1 / net core 3.1 seems to be an easy replacement.
Would you like a PR in for this?
https://github.com/streeva/jose-jwt/tree/netstandard21   is now working for our needs regarding A256GCM on Linux hosts.

**Comment by dvsekhvalnov** [comment]
Hi @gjermystreeva , sure PR's always welcome )

**Comment by ronnypmuliawan** [comment]
@dvsekhvalnov is there any updates on this issue?

**Comment by dvsekhvalnov** [comment]
Not much update from me folks. Sorry, crazy year, will try to find some time.

**Comment by dvsekhvalnov** [comment]
Released to nuget.
