### ISSUE TITLE
Vulnarabilities in multiple JWT libraries. What about JOSE-JWT?

### ISSUE THREAD

**Issue by JornWildt** [dvsekhvalnov/jose-jwt#6]
I was just pointed to this article here and wanted to know if there is something that needs to be done in JOSE-JWT?

See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by dvsekhvalnov** [comment]
Thanks @JornWildt, i'll examine against vulnerability this week.

**Comment by JornWildt** [comment]
It may just be a matter of telling devs to verify "correctly". The base problem is that attackers may simply replace the signature algorithm with "none" instead of the original "XXX" - thereby circumventing any signature checks ... unless implementors explicitly tells the verifier what algorithm to expect. Vulnerable implementations only looks at the "alg" in the header - which may easily be changed by an attacker.

**Comment by dvsekhvalnov** [comment]
Really don't see how it can apply to jose-jwt implementation:

1. every signature or encryption alg implementation verify type of key passed in to match alg type. You can't pass key to 'none' alg, it is expecting key to be 'null' and will throw exception otherwise.

2. same for replacing RSA key to HMAC algs expecting completely different types of keys (byte[] vs. RsaCryptoProvider types). I even didn't get how it is possible at all.

**Comment by dvsekhvalnov** [comment]
i think it is safe to close. @JornWildt feel free to reopen if you have any concerns.
