### ISSUE TITLE
Security namespace causing conflicts

### ISSUE THREAD

**Issue by thedustinsmith** [dvsekhvalnov/jose-jwt#97]
We have a `namespace Whatever.Security` elsewhere in our project.  When including jose-jwt, we're getting conflicts due to the `namespace Security.Cryptography`.  This conflict occurs when we're doing something like:

```csharp
using Whatever;
Security.DoStuff();
```

I'm wondering if there's a reason you're using that namespace as opposed to something like `Jose.Security.Cryptography`?

If you're open to this change, I can submit a PR.

**Comment by dvsekhvalnov** [comment]
Hi @thedustinsmith,

honestly i can't remember the reason, it was so long ago, probably no good real reason.

I don't mind to change namespaces but the issue is that it went public long ago, so really i can only do it for v3 to preserve semantic version (or kind of). And i don't have enough features to be qualified as v3 :)

**Comment by thedustinsmith** [comment]
Understandable.  I'll create the PR so you can have it if you want it.  No hard feelings if you don't merge it.

**Comment by breyed** [comment]
If you follow semver.org, you don't need any big features for a new major version, just a breaking change.

**Comment by dvsekhvalnov** [comment]
i'll try to include it along with #45

releasing new version just to introduce breaking change doesn't sound really sane to me ;)

**Comment by dvsekhvalnov** [comment]
We gonna rename namespace to: `Jose.keys` in upcoming 3.0 release

**Comment by dvsekhvalnov** [comment]
Released.
